apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: celis
rules:
- apiGroups:
  - "directpv.min.io"
  - "coordination.k8s.io"
  resources:
  - directpvdrives
  - directpvvolumes
  - directpvnodes
  - directpvinitrequests
  - events
  - leases
  verbs:
  - list
  - get
  - create
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - events
  verbs:
  - list
  - create
  - get
  - update
  - watch
