apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: directpv-operator-manager-role
rules:
- apiGroups:
  - directpv.min.io
  resources:
  - directpvdrives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
