apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: directpv-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Deployer is the Schema for the deployer's API
      displayName: Deployer
      kind: Deployer
      name: deployers.cache.example.com
      specDescriptors:
      - description: Port defines the port that will be used to init the container
          with the image
        displayName: Container Port
        path: containerPort
      - description: Size defines the number of Deployer instances
        displayName: Size
        path: size
      statusDescriptors:
      - description: Conditions store the status conditions of the Deployer instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: dp
  displayName: dp
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dp
  links:
  - name: Directpv Operator
    url: https://directpv-operator.domain
  maturity: alpha
  provider:
    name: dp
    url: dp
  version: 0.0.0
